### PR TITLE
CAD-896 adapt tx-gen to Release-1.11

### PR DESCRIPTION
**Pull request by CodiePP**
adapt tx-gen to node's Release-1.11

tested in cluster3nodes and it seems to work.

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
LGTM!

**Comment by deepfire** [comment]
bors merge

**Comment by deepfire** [comment]
bors merge

**Comment by deepfire** [comment]
bors merge already!

**Review by deepfire — APPROVED** [review]
LO AND BEHOLD, BORS, THOU SHALT NOTICE THIS APPROVAL IMMEDIATELY!

**Comment by deepfire** [comment]
bors merge

**Review by denisshevchenko — APPROVED** [review]

**Comment by deepfire** [comment]
bors merge already, please, I deplore you, for all that is holy and divine for your mechanistic conscience..

**Pull request merged**
