### PR TITLE
CAD-1309: Nodes grid view, beta-version

### PR DESCRIPTION
**Pull request by denisshevchenko**
Now it's possible to select one from two view modes:

1. Pane view (current one)
2. Grid view (the new one)

Grid view allows seeing metrics (received from nodes) side by side. Moreover, I can remove metrics I don't need, as well as remove nodes I don't need.

Please note that "beta-version" in the PR's title means that the grid view doesn't support drag-n-drop operations yet. Since re-arrangement of table's rows and/or column is not a trivial task and grid view can be used without it - I think this feature should be implemented as a separate issue.

### CODE REVIEW

**Review by deepfire — APPROVED** [review]

**Comment by denisshevchenko** [comment]
bors cancel

**Pull request merged**
