### PR TITLE
CAD-802: Charts view for resources.

### PR DESCRIPTION
**Pull request by denisshevchenko**
Now it's possible to see real-time resources not as progress bars only, but as charts as well. JS library `Chart.js` is used.

### CODE REVIEW

**Review by CodiePP — APPROVED** [review]
OK: the integrated Js library states: "Released under the MIT License"
:+1:  :100:

**Comment by denisshevchenko** [comment]
I rebased to `master` (because of `CODEOWNERS`). I'll repeat `bors` after checks are done.

**Pull request merged**
