### PR TITLE
SRE-60 full sync nightly benchmark

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Review by CodiePP — APPROVED** [review]
let's try...
thank you.

**Comment by mrBliss** [comment]
Is this going to run on a dedicated machine? If not, then the results will be skewed by the load on the CI machine.

**Comment by jbgi** [comment]
I'm setting up the dedicated agent. I'll ping once its operational.

**Comment by CodiePP** [comment]
> Is this going to run on a dedicated machine? If not, then the results will be skewed by the load on the CI machine.

yes, that's the plan.

**Pull request merged**
