### PR TITLE
CAD-1398: RTView installers (rebased on #170 + fixes)

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by CodiePP** [comment]
oh no! it errored out with "error: unable to fork: Cannot allocate memory"

**Comment by denisshevchenko** [comment]
Yes, the same OOM problem: https://hydra.iohk.io/jobset/Cardano/cardano-benchmarking-pr-171#tabs-errors

**Review by denisshevchenko — APPROVED** [review]
Now OOM error is fixed, and I see download links in all three builds.

**Pull request merged**
